#AWSTemplateFormatVersion : '2010-09-09'
#Transform: AWS::Serverless-2016-10-31
#Description: My first serverless application.
#
#Resources:
#  HelloFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      FunctionName: SamTemplateFunction
#      Timeout: 30
#      Handler: com.viacom.HelloLamda
#      Runtime: java8
#      CodeUrl: build/libs//lamda-1.0-SNAPSHOT.jar
#      Events:
#        sayHello:
#          Type: Api
#          Properties:
#            Path: /hello
#            Method: any
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SamTemplateFunction
      Timeout: 30
      Handler: com.viacom.Main::handleRequest
      Runtime: java8
      CodeUri: target//sam-java-template-1.0-SNAPSHOT.jar
      Policies:
        - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /hello/{proxy+}
            Method: any
  ExampleApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: swagger.yaml
Outputs:
  ExampleApi:
    Description: API URI
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello'
    Export:
Name: ExampleApi